// <auto-generated />
using InstrumentShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InstrumentShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327110625_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InstrumentShop.Shared.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fender Stratocaster",
                            Price = 1200m,
                            PurchasePrice = 0m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gibson Les Paul",
                            Price = 2500m,
                            PurchasePrice = 0m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Yamaha FG800",
                            Price = 350m,
                            PurchasePrice = 0m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ibanez SR300",
                            Price = 500m,
                            PurchasePrice = 0m,
                            StockQuantity = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
